In [2]:
# 1. Import numpy as np and see the version
import numpy as np
np.__version__

'1.14.2'

In [6]:
# 2. How to create a 1D array?
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 3. How to create a boolean array?
np.full((3,3), False, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [8]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
# 4. How to extract items that satisfy a given condition from 1D array?
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [10]:
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])

In [11]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
arr[arr%2 == 1] = -1

In [12]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [3]:
# 6. How to replace items that satisfy a condition without affecting the original array?
arr1 = np.arange(10)
out = np.where(arr1%2 == 1, -1, arr1)
print(arr1)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [21]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 7. How to reshape an array?
arr2 = np.arange(12)
arr2.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
# 8. How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.r_[a,b] # row-wise stacking of arrays

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
# 9. How to stack two arrays horizontally?
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [37]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [38]:
np.c_[a,b] # column-wise stacking of arrays

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [40]:
# 10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [41]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [42]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [43]:
# 11. How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [44]:
np.intersect1d(a,b)

array([2, 4])

In [45]:
# 12. How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [46]:
a-b

array([-4, -4, -4, -4, -4])

In [47]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [48]:
# 13. How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [49]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [50]:
# 14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [59]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [60]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [61]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])