# 1. Import numpy as np and see the version

In [83]:
import numpy as np
np.__version__

'1.14.2'

# 2. How to create a 1D array?

In [84]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. How to create a boolean array?

In [85]:
np.full((3,3), False, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [86]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?

In [87]:
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [88]:
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])

# 5. How to replace items that satisfy a condition with another value in numpy array?

In [89]:
arr[arr%2 == 1] = -1

In [90]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6. How to replace items that satisfy a condition without affecting the original array?

In [91]:
arr1 = np.arange(10)
out = np.where(arr1%2 == 1, -1, arr1)
print(arr1)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [92]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7. How to reshape an array?

In [93]:
arr2 = np.arange(12)
arr2.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 8. How to stack two arrays vertically?

In [94]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [95]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [96]:
np.r_[a,b] # row-wise stacking of arrays

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 9. How to stack two arrays horizontally?

In [97]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [98]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [99]:
np.c_[a,b] # column-wise stacking of arrays

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10. How to generate custom sequences in numpy without hardcoding?

In [100]:
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [101]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [102]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?

In [103]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [104]:
np.intersect1d(a,b)

array([2, 4])

# 12. How to remove from one array those items that exist in another?

In [105]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [106]:
a-b

array([-4, -4, -4, -4, -4])

In [107]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 13. How to get the positions where elements of two arrays match?

In [108]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [109]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# 14. How to extract all numbers between a given range from a numpy array?

In [110]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [111]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [112]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [113]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

# 15. How to make a python function that handles scalars to work on numpy arrays?

In [114]:
def maxx(x, y):
    if x>y:
        return x
    else:
        return y

maxx(1,5)

5

In [119]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [116]:
len(a)

7

In [121]:
# how I'd write the function in python
def pair_min(x,y):
#     if len(x) != len(y):
#         return 0
    c = np.repeat(0, len(x))
    i = 0
    while i < len(x):
        if x[i] < y[i]:
            c[i] = x[i]
        else:
            c[i] = y[i]
        i = i+1
        
    return c

pair_min(a,b)

array([5, 3, 4, 8, 6, 4, 1])

In [122]:
pair_max = np.vectorize(maxx)
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

# 16. How to swap two columns in a 2d numpy array?

In [126]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 17. How to swap two rows in a 2d numpy array?

In [128]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18. How to reverse the rows of a 2D array?

In [130]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [131]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 19. How to reverse the columns of a 2D array?

In [135]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [136]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 20. How to create a 2D array containing random floats between 5 and 10?