# 1. Import numpy as np and see the version

In [1]:
import numpy as np
np.__version__

'1.14.2'

# 2. How to create a 1D array?

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. How to create a boolean array?

In [3]:
np.full((3,3), False, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?

In [5]:
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [6]:
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])

# 5. How to replace items that satisfy a condition with another value in numpy array?

In [7]:
arr[arr%2 == 1] = -1

In [8]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6. How to replace items that satisfy a condition without affecting the original array?

In [9]:
arr1 = np.arange(10)
out = np.where(arr1%2 == 1, -1, arr1)
print(arr1)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7. How to reshape an array?

In [11]:
arr2 = np.arange(12)
arr2.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 8. How to stack two arrays vertically?

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.r_[a,b] # row-wise stacking of arrays

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 9. How to stack two arrays horizontally?

In [15]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
np.c_[a,b] # column-wise stacking of arrays

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10. How to generate custom sequences in numpy without hardcoding?

In [18]:
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [19]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [22]:
np.intersect1d(a,b)

array([2, 4])

# 12. How to remove from one array those items that exist in another?

In [23]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [24]:
a-b

array([-4, -4, -4, -4, -4])

In [25]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 13. How to get the positions where elements of two arrays match?

In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [27]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# 14. How to extract all numbers between a given range from a numpy array?

In [28]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [29]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [30]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [31]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

# 15. How to make a python function that handles scalars to work on numpy arrays?

In [32]:
def maxx(x, y):
    if x>y:
        return x
    else:
        return y

maxx(1,5)

5

In [33]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [34]:
len(a)

7

In [35]:
# how I'd write the function in python
def pair_min(x,y):
#     if len(x) != len(y):
#         return 0
    c = np.repeat(0, len(x))
    i = 0
    while i < len(x):
        if x[i] < y[i]:
            c[i] = x[i]
        else:
            c[i] = y[i]
        i = i+1
        
    return c

pair_min(a,b)

array([5, 3, 4, 8, 6, 4, 1])

In [36]:
pair_max = np.vectorize(maxx)
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

# 16. How to swap two columns in a 2d numpy array?

In [37]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 17. How to swap two rows in a 2d numpy array?

In [39]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18. How to reverse the rows of a 2D array?

In [41]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [42]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 19. How to reverse the columns of a 2D array?

In [43]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [44]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 20. How to create a 2D array containing random floats between 5 and 10?

In [45]:
rand_arr1 = np.random.randint(low=5, high=10, size = (5,3))
rand_arr1

array([[9, 7, 5],
       [7, 6, 8],
       [9, 7, 8],
       [7, 8, 7],
       [6, 9, 9]])

In [46]:
rand_arr2 = np.random.random((5,3))
rand_arr2

array([[0.42576583, 0.44016366, 0.71299617],
       [0.2931304 , 0.07807623, 0.8591583 ],
       [0.83723426, 0.77492597, 0.84404056],
       [0.12522133, 0.68310469, 0.37721145],
       [0.36864754, 0.87485285, 0.88798752]])

In [47]:
rand_arr = rand_arr1 + rand_arr2
rand_arr

array([[9.42576583, 7.44016366, 5.71299617],
       [7.2931304 , 6.07807623, 8.8591583 ],
       [9.83723426, 7.77492597, 8.84404056],
       [7.12522133, 8.68310469, 7.37721145],
       [6.36864754, 9.87485285, 9.88798752]])

In [48]:
rand_arr = np.random.uniform(5, 10, size=(5,3))
rand_arr

array([[7.69506822, 6.38185756, 5.25094767],
       [7.38455433, 6.56516814, 5.443013  ],
       [8.38687742, 8.27877119, 6.80009195],
       [6.70966448, 8.9919388 , 9.76119776],
       [6.40350048, 6.85483501, 7.79942884]])

# 21. How to print only 3 decimal places in python numpy array?

In [49]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.16795911, 0.58123217, 0.97485997],
       [0.66586457, 0.34478531, 0.70298715],
       [0.35191127, 0.32735576, 0.60564123],
       [0.8922681 , 0.15259501, 0.49774169],
       [0.34440746, 0.01315117, 0.94298062]])

In [50]:
np.set_printoptions(precision=3)
rand_arr

array([[0.168, 0.581, 0.975],
       [0.666, 0.345, 0.703],
       [0.352, 0.327, 0.606],
       [0.892, 0.153, 0.498],
       [0.344, 0.013, 0.943]])

# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [51]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [52]:
np.set_printoptions(suppress=False)
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [53]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

# 23. How to limit the number of items printed in output of numpy array?

In [54]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

# 24. How to print the full numpy array without truncating

In [56]:
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [57]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

# 26. How to extract a particular column from 1D array of tuples?

In [58]:
iris_ld = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_ld.shape)

(150,)


c:\users\kweus\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [59]:
species = np.array([row[4] for row in iris_ld])
species[:5]
print(species[:5].shape)

(5,)


# 27. How to convert a 1d array of tuples to a 2d numpy array?

In [60]:
iris_2d = np.array([row.tolist()[:4] for row in iris_ld])
iris_2d.shape
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [61]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1,2,4])
iris_2d[:4]

array([[3.5, 1.4, nan],
       [3. , 1.4, nan],
       [3.2, 1.3, nan],
       [3.1, 1.5, nan]])

# 28. How to compute the mean, median, standard deviation of a numpy array?

In [62]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [63]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [64]:
mean, median, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mean, median, sd)

5.843333333333334 5.8 0.8253012917851409


# 29. How to normalize an array so the values range exactly between 0 and 1?

In [65]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
Smax, Smin = sepallength.max(), sepallength.min()
print(Smax, Smin)

7.9 4.3


In [66]:
Smax-Smin

3.6000000000000005

In [67]:
sepallength-Smin

array([0.8, 0.6, 0.4, 0.3, 0.7, 1.1, 0.3, 0.7, 0.1, 0.6, 1.1, 0.5, 0.5,
       0. , 1.5, 1.4, 1.1, 0.8, 1.4, 0.8, 1.1, 0.8, 0.3, 0.8, 0.5, 0.7,
       0.7, 0.9, 0.9, 0.4, 0.5, 1.1, 0.9, 1.2, 0.6, 0.7, 1.2, 0.6, 0.1,
       0.8, 0.7, 0.2, 0.1, 0.7, 0.8, 0.5, 0.8, 0.3, 1. , 0.7, 2.7, 2.1,
       2.6, 1.2, 2.2, 1.4, 2. , 0.6, 2.3, 0.9, 0.7, 1.6, 1.7, 1.8, 1.3,
       2.4, 1.3, 1.5, 1.9, 1.3, 1.6, 1.8, 2. , 1.8, 2.1, 2.3, 2.5, 2.4,
       1.7, 1.4, 1.2, 1.2, 1.5, 1.7, 1.1, 1.7, 2.4, 2. , 1.3, 1.2, 1.2,
       1.8, 1.5, 0.7, 1.3, 1.4, 1.4, 1.9, 0.8, 1.4, 2. , 1.5, 2.8, 2. ,
       2.2, 3.3, 0.6, 3. , 2.4, 2.9, 2.2, 2.1, 2.5, 1.4, 1.5, 2.1, 2.2,
       3.4, 3.4, 1.7, 2.6, 1.3, 3.4, 2. , 2.4, 2.9, 1.9, 1.8, 2.1, 2.9,
       3.1, 3.6, 2.1, 2. , 1.8, 3.4, 2. , 2.1, 1.7, 2.6, 2.4, 2.6, 1.5,
       2.5, 2.4, 2.4, 2. , 2.2, 1.9, 1.6])

In [68]:
(sepallength-Smin)/(Smax-Smin)

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

In [69]:
(sepallength - Smin)/sepallength.ptp()

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

In [70]:
sepallength.ptp() # peak to peak values

3.6000000000000005

# 30. How to compute the softmax score?

In [73]:
def softmax(x): # Dunno wtf this is but will explore later on
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)
print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

# 31. How to find the percentile scores of a numpy array?

In [74]:
np.percentile(sepallength, q=[5,95])

array([4.6  , 7.255])

# 32. How to insert values at random positions in an array?

In [76]:
# Q. Insert np.nan values at 20 random positions in iris_2d dataset
i, j = np.where(iris_2d) # i, j contain the row numbers and column numbers of 600(150rows * 4columns) elements of iris_x

In [79]:
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan