In [4]:
# 1. Import numpy as np and see the version
import numpy as np
np.__version__

'1.14.2'

In [6]:
# 2. How to create a 1D array?
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 3. How to create a boolean array?
np.full((3,3), False, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [8]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
# 4. How to extract items that satisfy a given condition from 1D array?
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [10]:
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])

In [11]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
arr[arr%2 == 1] = -1

In [12]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
# 6. How to replace items that satisfy a condition without affecting the original array?
arr1 = np.arange(10)
out = np.where(arr1%2 == 1, -1, arr1)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [21]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])