# 1. Import numpy as np and see the version

In [71]:
import numpy as np
np.__version__

'1.14.2'

# 2. How to create a 1D array?

In [72]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. How to create a boolean array?

In [73]:
np.full((3,3), False, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [74]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?

In [75]:
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [76]:
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])

# 5. How to replace items that satisfy a condition with another value in numpy array?

In [77]:
arr[arr%2 == 1] = -1

In [78]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6. How to replace items that satisfy a condition without affecting the original array?

In [79]:
arr1 = np.arange(10)
out = np.where(arr1%2 == 1, -1, arr1)
print(arr1)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [80]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7. How to reshape an array?

In [81]:
arr2 = np.arange(12)
arr2.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 8. How to stack two arrays vertically?

In [82]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [83]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [84]:
np.r_[a,b] # row-wise stacking of arrays

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 9. How to stack two arrays horizontally?

In [85]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [86]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [87]:
np.c_[a,b] # column-wise stacking of arrays

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10. How to generate custom sequences in numpy without hardcoding?

In [88]:
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [89]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [90]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?

In [91]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [92]:
np.intersect1d(a,b)

array([2, 4])

# 12. How to remove from one array those items that exist in another?

In [93]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [94]:
a-b

array([-4, -4, -4, -4, -4])

In [95]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 13. How to get the positions where elements of two arrays match?

In [96]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [97]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# 14. How to extract all numbers between a given range from a numpy array?

In [98]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [99]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [100]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [101]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

# 15. How to make a python function that handles scalars to work on numpy arrays?

In [102]:
def maxx(x, y):
    if x>y:
        return x
    else:
        return y

maxx(1,5)

5

In [103]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [104]:
len(a)

7

In [105]:
# how I'd write the function in python
def pair_min(x,y):
#     if len(x) != len(y):
#         return 0
    c = np.repeat(0, len(x))
    i = 0
    while i < len(x):
        if x[i] < y[i]:
            c[i] = x[i]
        else:
            c[i] = y[i]
        i = i+1
        
    return c

pair_min(a,b)

array([5, 3, 4, 8, 6, 4, 1])

In [106]:
pair_max = np.vectorize(maxx)
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

# 16. How to swap two columns in a 2d numpy array?

In [107]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [108]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 17. How to swap two rows in a 2d numpy array?

In [109]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18. How to reverse the rows of a 2D array?

In [111]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [112]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 19. How to reverse the columns of a 2D array?

In [113]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [114]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 20. How to create a 2D array containing random floats between 5 and 10?

In [115]:
rand_arr1 = np.random.randint(low=5, high=10, size = (5,3))
rand_arr1

array([[5, 9, 8],
       [9, 7, 5],
       [8, 6, 7],
       [8, 9, 9],
       [6, 8, 9]])

In [116]:
rand_arr2 = np.random.random((5,3))
rand_arr2

array([[0.632384, 0.699359, 0.641965],
       [0.920024, 0.298876, 0.568746],
       [0.178624, 0.532574, 0.646691],
       [0.142065, 0.581389, 0.47919 ],
       [0.386419, 0.440465, 0.404757]])

In [117]:
rand_arr = rand_arr1 + rand_arr2
rand_arr

array([[5.632384, 9.699359, 8.641965],
       [9.920024, 7.298876, 5.568746],
       [8.178624, 6.532574, 7.646691],
       [8.142065, 9.581389, 9.47919 ],
       [6.386419, 8.440465, 9.404757]])

In [118]:
rand_arr = np.random.uniform(5, 10, size=(5,3))
rand_arr

array([[7.21127 , 5.150616, 8.880027],
       [7.754792, 6.905367, 7.646329],
       [9.784385, 5.879107, 5.591514],
       [9.314728, 5.374334, 9.125474],
       [9.180659, 5.376975, 5.057004]])

# 21. How to print only 3 decimal places in python numpy array?

In [119]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.048421, 0.357123, 0.665693],
       [0.01139 , 0.107918, 0.901013],
       [0.794879, 0.811461, 0.640278],
       [0.62478 , 0.145508, 0.570216],
       [0.065112, 0.313413, 0.217066]])

In [120]:
np.set_printoptions(precision=3)
rand_arr

array([[0.048, 0.357, 0.666],
       [0.011, 0.108, 0.901],
       [0.795, 0.811, 0.64 ],
       [0.625, 0.146, 0.57 ],
       [0.065, 0.313, 0.217]])

# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [121]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

In [122]:
np.set_printoptions(suppress=False)
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [123]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

# 23. How to limit the number of items printed in output of numpy array?

In [124]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [125]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

# 24. How to print the full numpy array without truncating

In [126]:
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [127]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

# 26. How to extract a particular column from 1D array of tuples?

In [128]:
iris_ld = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_ld.shape)

(150,)


c:\users\kweus\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [129]:
species = np.array([row[4] for row in iris_ld])
species[:5]
print(species[:5].shape)

(5,)


# 27. How to convert a 1d array of tuples to a 2d numpy array?

In [130]:
iris_2d = np.array([row.tolist()[:4] for row in iris_ld])
iris_2d.shape
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [131]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1,2,4])
iris_2d[:4]

array([[3.5, 1.4, nan],
       [3. , 1.4, nan],
       [3.2, 1.3, nan],
       [3.1, 1.5, nan]])

# 28. How to compute the mean, median, standard deviation of a numpy array?

In [132]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [133]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [134]:
mean, median, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mean, median, sd)

5.843333333333334 5.8 0.8253012917851409


# 29. How to normalize an array so the values range exactly between 0 and 1?

In [135]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
Smax, Smin = sepallength.max(), sepallength.min()
print(Smax, Smin)

7.9 4.3


In [136]:
Smax-Smin

3.6000000000000005

In [137]:
sepallength-Smin

array([0.8, 0.6, 0.4, 0.3, 0.7, 1.1, 0.3, 0.7, 0.1, 0.6, 1.1, 0.5, 0.5,
       0. , 1.5, 1.4, 1.1, 0.8, 1.4, 0.8, 1.1, 0.8, 0.3, 0.8, 0.5, 0.7,
       0.7, 0.9, 0.9, 0.4, 0.5, 1.1, 0.9, 1.2, 0.6, 0.7, 1.2, 0.6, 0.1,
       0.8, 0.7, 0.2, 0.1, 0.7, 0.8, 0.5, 0.8, 0.3, 1. , 0.7, 2.7, 2.1,
       2.6, 1.2, 2.2, 1.4, 2. , 0.6, 2.3, 0.9, 0.7, 1.6, 1.7, 1.8, 1.3,
       2.4, 1.3, 1.5, 1.9, 1.3, 1.6, 1.8, 2. , 1.8, 2.1, 2.3, 2.5, 2.4,
       1.7, 1.4, 1.2, 1.2, 1.5, 1.7, 1.1, 1.7, 2.4, 2. , 1.3, 1.2, 1.2,
       1.8, 1.5, 0.7, 1.3, 1.4, 1.4, 1.9, 0.8, 1.4, 2. , 1.5, 2.8, 2. ,
       2.2, 3.3, 0.6, 3. , 2.4, 2.9, 2.2, 2.1, 2.5, 1.4, 1.5, 2.1, 2.2,
       3.4, 3.4, 1.7, 2.6, 1.3, 3.4, 2. , 2.4, 2.9, 1.9, 1.8, 2.1, 2.9,
       3.1, 3.6, 2.1, 2. , 1.8, 3.4, 2. , 2.1, 1.7, 2.6, 2.4, 2.6, 1.5,
       2.5, 2.4, 2.4, 2. , 2.2, 1.9, 1.6])

In [138]:
(sepallength-Smin)/(Smax-Smin)

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

In [139]:
(sepallength - Smin)/sepallength.ptp()

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

In [140]:
sepallength.ptp() # peak to peak values

3.6000000000000005

# 30. How to compute the softmax score?