# 1. Import numpy as np and see the version

In [1]:
import numpy as np
np.__version__

'1.14.2'

# 2. How to create a 1D array?

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. How to create a boolean array?

In [3]:
np.full((3,3), False, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?

In [5]:
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [6]:
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])

# 5. How to replace items that satisfy a condition with another value in numpy array?

In [7]:
arr[arr%2 == 1] = -1

In [8]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6. How to replace items that satisfy a condition without affecting the original array?

In [9]:
arr1 = np.arange(10)
out = np.where(arr1%2 == 1, -1, arr1)
print(arr1)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7. How to reshape an array?

In [11]:
arr2 = np.arange(12)
arr2.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 8. How to stack two arrays vertically?

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.r_[a,b] # row-wise stacking of arrays

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 9. How to stack two arrays horizontally?

In [15]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
np.c_[a,b] # column-wise stacking of arrays

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10. How to generate custom sequences in numpy without hardcoding?

In [18]:
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [19]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [22]:
np.intersect1d(a,b)

array([2, 4])

# 12. How to remove from one array those items that exist in another?

In [23]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [24]:
a-b

array([-4, -4, -4, -4, -4])

In [25]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 13. How to get the positions where elements of two arrays match?

In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [27]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# 14. How to extract all numbers between a given range from a numpy array?

In [28]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [29]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [30]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [31]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

# 15. How to make a python function that handles scalars to work on numpy arrays?

In [32]:
def maxx(x, y):
    if x>y:
        return x
    else:
        return y

maxx(1,5)

5

In [33]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [34]:
len(a)

7

In [35]:
# how I'd write the function in python
def pair_min(x,y):
#     if len(x) != len(y):
#         return 0
    c = np.repeat(0, len(x))
    i = 0
    while i < len(x):
        if x[i] < y[i]:
            c[i] = x[i]
        else:
            c[i] = y[i]
        i = i+1
        
    return c

pair_min(a,b)

array([5, 3, 4, 8, 6, 4, 1])

In [36]:
pair_max = np.vectorize(maxx)
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

# 16. How to swap two columns in a 2d numpy array?

In [37]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 17. How to swap two rows in a 2d numpy array?

In [39]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18. How to reverse the rows of a 2D array?

In [41]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [42]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 19. How to reverse the columns of a 2D array?

In [43]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [44]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 20. How to create a 2D array containing random floats between 5 and 10?

In [53]:
rand_arr1 = np.random.randint(low=5, high=10, size = (5,3))
rand_arr1

array([[9, 7, 7],
       [9, 7, 6],
       [8, 9, 6],
       [6, 9, 8],
       [8, 7, 9]])

In [55]:
rand_arr2 = np.random.random((5,3))
rand_arr2

array([[0.70927741, 0.48455048, 0.8793755 ],
       [0.64074244, 0.72597552, 0.97523482],
       [0.43033333, 0.01750107, 0.14778346],
       [0.8409704 , 0.98230277, 0.79045131],
       [0.81414454, 0.37488887, 0.21111982]])

In [57]:
rand_arr = rand_arr1 + rand_arr2
rand_arr

array([[9.70927741, 7.48455048, 7.8793755 ],
       [9.64074244, 7.72597552, 6.97523482],
       [8.43033333, 9.01750107, 6.14778346],
       [6.8409704 , 9.98230277, 8.79045131],
       [8.81414454, 7.37488887, 9.21111982]])

In [59]:
rand_arr = np.random.uniform(5, 10, size=(5,3))
rand_arr

array([[6.40245307, 9.64980838, 7.7524822 ],
       [6.09899776, 5.60019564, 6.44474862],
       [7.2232095 , 7.3244761 , 7.41541457],
       [7.52112662, 6.23442725, 9.36190998],
       [6.06079113, 6.92337586, 8.56727055]])

# 21. How to print only 3 decimal places in python numpy array?

In [63]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.69574457, 0.53965397, 0.969505  ],
       [0.41732773, 0.85431099, 0.22518455],
       [0.50696862, 0.76184   , 0.03796374],
       [0.35382974, 0.46743413, 0.27721822],
       [0.65858633, 0.60313318, 0.39209469]])

In [64]:
np.set_printoptions(precision=3)
rand_arr

array([[0.696, 0.54 , 0.97 ],
       [0.417, 0.854, 0.225],
       [0.507, 0.762, 0.038],
       [0.354, 0.467, 0.277],
       [0.659, 0.603, 0.392]])

# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [71]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [75]:
np.set_printoptions(suppress=False)
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])